Pages/CreateBlog.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PublicProject.Models;
using PublicProject.Services;

namespace PublicProject.Pages
{
    public class CreateBlogModel : PageModel
    {
        public readonly UtilitiesToBeScoped ScopedData;
        static int blogpostid;
       
        public int subcategoryid { get; set; }

        [BindProperty]
        public IFormFile UploadedImage { get; set; }

        public CreateBlogModel(UtilitiesToBeScoped utilitiesToBeScoped)
        {
            ScopedData = utilitiesToBeScoped;         
        }
        [BindProperty]
        public Blog Blog { get; set; } = default!;
        public IActionResult OnGet(int SubCategoryId)
        {

            subcategoryid = SubCategoryId;
 
            return Page();

        }
        public async Task<IActionResult> OnPostAsync(int SubCategoryId)
        {
            string fileName = string.Empty;
           
            if (UploadedImage != null)
            {
                Random rnd = new();
                fileName = rnd.Next(0, 100000).ToString() + UploadedImage.FileName;
                var file = "./wwwroot/img/" + fileName;
                using (var fileStream = new FileStream(file, FileMode.Create))
                {
                    await UploadedImage.CopyToAsync(fileStream);
                }
            }
            else
            {
                fileName = "ingenbildbild.jpg";
            }
            Blog.Image = fileName;
            blogpostid = SubCategoryId;

            ScopedData.DBContext.Blogs.Add(Blog);
            await ScopedData.DBContext.SaveChangesAsync();

            return RedirectToPage("/Viewforumpost", new { id = Blog.Id });
        }


    }

}

Pages/EditBlog.cshtml.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PublicProject.Data;
using PublicProject.Models;
using PublicProject.Services;

namespace PublicProject.Pages
{
    public class EditBlogModel : PageModel
    {
        public readonly UtilitiesToBeScoped ScopedData;

        [BindProperty]
        public Blog Blog { get; set; } = default!;

        public EditBlogModel(UtilitiesToBeScoped utilitiesToBeScoped)
        {
            ScopedData = utilitiesToBeScoped;
            
        }

        [BindProperty]
        public IFormFile UploadedImage { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || ScopedData.DBContext.Blogs == null)
            {
                return NotFound();
            }

            var blog = await ScopedData.DBContext.Blogs.FirstOrDefaultAsync(m => m.Id == id);

            if (blog == null)
            {
                return NotFound();
            }
            Blog = blog;
            return Page();
        }
        public async Task<IActionResult> OnPostAsync()
        {
            var oldblog = ScopedData.DBContext.Blogs.FirstOrDefault(b => b.Id == Blog.Id);
            string fileName = string.Empty;
        
            if (UploadedImage != null)
            {
                Random rnd = new();
                fileName = rnd.Next(0, 100000).ToString() + UploadedImage.FileName;
                var file = "./wwwroot/img/" + fileName;
                using (var fileStream = new FileStream(file, FileMode.Create))
                {
                    await UploadedImage.CopyToAsync(fileStream);
                }
            }
            else
            {
                fileName = Blog.Image;

                if(fileName== null)
                {
                    fileName = "ingenbildbild.jpg";
                }
            }

        
           
            oldblog.Image = fileName;   
            oldblog.Title = Blog.Title;
            oldblog.Text = Blog.Text;
          
            await ScopedData.DBContext.SaveChangesAsync();
            
            return RedirectToPage("./Viewforumpost", new { id = Blog.Id } );
        }
       
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace PublicProject.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PublicProject.Models;
using PublicProject.Services;
using System.Security.Claims;

namespace PublicProject.Pages
{
    public class IndexModel : PageModel
    {
        public readonly UtilitiesToBeScoped ScopedData;

        public IndexModel(UtilitiesToBeScoped utilitiesToBeScoped)
        {
            ScopedData = utilitiesToBeScoped;
        }
    }
}

Pages/OldIndex.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PublicProject.Models;
using System.Security.Claims;

namespace PublicProject.Pages
{
    public class OldIndexModel : PageModel
    {
        private readonly Data.ApplicationDbContext _context;
        
        public OldIndexModel(Data.ApplicationDbContext context)
        {
            _context = context;
        }
        public  List<Models.Blog> Blogs { get; set; }

        [BindProperty]
        public Models.Blog Blog { get; set; }

        [BindProperty]
        public IFormFile UploadedImage { get; set; }
        public async Task<IActionResult> OnGetAsync(int deleteid)
        {
            if (deleteid != 0)
            {
                Models.Blog blog = await _context.Blog.FindAsync(deleteid);

                if (blog != null)
                {
                    if (System.IO.File.Exists("./wwwroot/img/" + blog.Image))
                    {
                        System.IO.File.Delete("./wwwroot/img/" + blog.Image);
                    }
                    _context.Blog.Remove(blog);
                    await _context.SaveChangesAsync();

                    return RedirectToPage("./Index");
                }
            }

            Blogs = await _context.Blog.ToListAsync();


            return Page();
        }
        public async Task<IActionResult> OnGetAsync2()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            string fileName = string.Empty;

            // Generarar ett relativt unikt fil namn så att det inte finns 100 filer med samma namn.
            if (UploadedImage != null)
            {
                Random rnd = new Random();
                fileName = rnd.Next(1, 100000).ToString() + UploadedImage.FileName;
                var file = "./wwwroot/img/" + fileName;

                using (var fileStream = new FileStream(file, FileMode.Create))
                {
                    await UploadedImage.CopyToAsync(fileStream);
                }
            }
            Blog.Date = DateTime.Now;
            Blog.Image = fileName;
            Blog.UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            _context.Add(Blog);

            await _context.SaveChangesAsync();


            return RedirectToPage("./Index");
        }



      
    }
}

Pages/Overview.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PublicProject.Models;
using PublicProject.Services;
using System.Security.Claims;

namespace PublicProject.Pages
{
    public class OverviewModel : PageModel
    {
        public readonly UtilitiesToBeScoped ScopedData;
        public OverviewModel(UtilitiesToBeScoped utilitiesToBeScoped)
        {
            ScopedData = utilitiesToBeScoped;
        }

        [BindProperty]
        public Models.UserProfile UserProfile { get; set; }

        [BindProperty]
        public IFormFile UploadedImage { get; set; }
        public async Task<IActionResult> OnGetAsync() 
        {
            return Page();
        }


        static string fileName = string.Empty;
        public async Task<IActionResult> OnPostAsync()  
        {
            //string fileName = string.Empty; 

            if (UploadedImage != null)
            {
                Random rnd = new();
                fileName = UploadedImage.FileName;
                var file = "./wwwroot/img/" + fileName;
                using (var fileStream = new FileStream(file, FileMode.Create))
                {
                    await UploadedImage.CopyToAsync(fileStream);
                }
            }
            else
            {
                fileName = "defaultuserpng.jpg";
            }

            UserProfile existingProfile = ScopedData.DBContext.UserProfiles.FirstOrDefault(p => p.UserId == User.FindFirstValue(ClaimTypes.NameIdentifier));

            if (existingProfile != null)
            {
                // Update the existing profile if found
                existingProfile.Imglink = fileName;
                existingProfile.UserName = UserProfile.UserName;
            }
            else
            {
                // Create a new profile if it doesn't exist
                UserProfile newProfile = new UserProfile
                {
                    Imglink = fileName,
                    UserId = User.FindFirstValue(ClaimTypes.NameIdentifier),
                    UserName = UserProfile.UserName
                };
                ScopedData.DBContext.Add(newProfile);
            }

            await ScopedData.DBContext.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PublicProject.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/SendmessageToUserView.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PublicProject.Models;
using PublicProject.Services;

namespace PublicProject.Pages
{
    public class SendmessageToUserViewModel : PageModel
    {
        public readonly UtilitiesToBeScoped ScopedData;
        public SendmessageToUserViewModel(UtilitiesToBeScoped utilitiesToBeScoped)
        {
            ScopedData = utilitiesToBeScoped;
        }
        public string userid { get; set; }

        [BindProperty]
        public Message Message { get; set; } = default!;

        [BindProperty]
        public Report Report { get; set; } = default!;
        public IActionResult OnGet(string id)
        {
          
            userid = id;
            return Page();
        }
        public async Task<IActionResult> OnPostAsync()
        {
           

            ScopedData.DBContext.Messages.Add(Message);
            await ScopedData.DBContext.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/ShowAllMyBlogs.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PublicProject.Services;

namespace PublicProject.Pages
{
    public class ShowAllMyBlogsModel : PageModel
    {
        public readonly UtilitiesToBeScoped ScopedData;
        public List<Models.Blog> Blogs { get; set; }
        public ShowAllMyBlogsModel(UtilitiesToBeScoped utilitiesToBeScoped)
        {
            ScopedData = utilitiesToBeScoped;
        }
        public void OnGet(string id)
        {
            Blogs = ScopedData.Blogs.Where(x => x.UserId == id).ToList();
        }
    }
}

Pages/SubCategories.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PublicProject.Models;
using System.Security.Claims;

namespace PublicProject.Pages
{
    //    public class SubCategories 
    //    {

    //        public 
    //        public static string LimitLength(this string source, int maxLength)
    //        {
    //            if (source != null)
    //            {
    //                if (source.Length <= maxLength)
    //                {
    //                    return source;
    //                }

    //                return source.Substring(0, maxLength);
    //            }
    //            return source;
    //        }

    //    }
    //}
}

Pages/SubcategoryViewer.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using PublicProject.Models;
using PublicProject.Services;

namespace PublicProject.Pages
{
    public class NewSubcategoriesModel : PageModel
    {

        public readonly UtilitiesToBeScoped ScopedData;

        public NewSubcategoriesModel(UtilitiesToBeScoped utilitiesToBeScoped)
        {
            ScopedData = utilitiesToBeScoped;
        }

        public IActionResult OnGet(int id)
        {
            ScopedData.category = ScopedData.DBContext.Categories.Find(id);
            ScopedData.DBContext.SaveChanges();
            return Page();
        }
    }
}

Pages/Topicbrowser.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PublicProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using PublicProject.Models;
using PublicProject.Services;

namespace PublicProject.Pages
{
    public class Topicbrowser  : PageModel
    {

        public readonly UtilitiesToBeScoped ScopedData;

        public Topicbrowser(UtilitiesToBeScoped utilitiesToBeScoped)
        {
            ScopedData = utilitiesToBeScoped;
        }
        
        public IActionResult OnGet()
        {
            return Page();
        }
    }
}

Pages/ViewAllBlogs.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PublicProject.Models;
using PublicProject.Services;
using System.Diagnostics.Metrics;

namespace PublicProject.Pages
{
    public class ViewBlogModel : PageModel
    {
        public readonly UtilitiesToBeScoped ScopedData;

        public ViewBlogModel(UtilitiesToBeScoped utilitiesToBeScoped)
        {
            ScopedData = utilitiesToBeScoped;
        }

        [BindProperty(SupportsGet =true)]
        public int SubCategoryId { get; set; }
      
        public IActionResult OnGet()
        {
            var x = SubCategoryId;

            return Page();
        }
    }
}

Pages/ViewForumPost.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.EntityFrameworkCore;
using PublicProject.Models;
using PublicProject.Services;

namespace PublicProject.Pages
{
    public class ViewForumPostModel : PageModel
    {

        public readonly UtilitiesToBeScoped ScopedData;
        
        public ViewForumPostModel(UtilitiesToBeScoped utilitiesToBeScoped) 
        {
            ScopedData = utilitiesToBeScoped;
        }
        
        [BindProperty]
        public Comment Comment { get; set; } = default!;

        [BindProperty]
        public Message Message { get; set; } = default!;

        [BindProperty]
        public Report Report { get; set; } = default!;

        static int blogpostid;

        public async Task<IActionResult> OnGetAsync(int id)
        {
            ScopedData.blog = await ScopedData.DBContext.Blogs.FindAsync(id);

            if (ScopedData.blog.Popularity == null)
            {
                ScopedData.blog.Popularity = 0;
            }

            ScopedData.blog.Popularity++;

            blogpostid = id;

            if (ScopedData.blog == null)
            {
                return NotFound();
            }

           await ScopedData.DBContext.SaveChangesAsync();

            return Page();
        }
        public async Task<IActionResult> OnPostSendCommentAsync()
        {
            await ScopedData.DBContext.Comments.AddAsync(Comment);
            await ScopedData.DBContext.SaveChangesAsync();

            return RedirectToPage("/ViewForumPost", new { id = blogpostid });
        }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD


        public async Task<IActionResult> OnPostReportAsync()
        {
            //if (!ModelState.IsValid)
            //{
            //    return Page();
            //}

            ScopedData.DBContext.Reports.Add(Report);
            await ScopedData.DBContext.SaveChangesAsync();

            return RedirectToPage("/ViewForumPost", new { id = blogpostid });
        }

   
    }
}

Pages/EditBlog.cshtml
@page
@model PublicProject.Pages.EditBlogModel
@{
}
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Blog.Id" />
            <div class="form-group">
                <label asp-for="Blog.Title" class="control-label"></label>
                <input asp-for="Blog.Title" class="form-control" />
                <span asp-validation-for="Blog.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Blog.Text" class="control-label"></label>
                <input asp-for="Blog.Text" class="form-control" />
                <span asp-validation-for="Blog.Text" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <label asp-for="Blog.Date" class="control-label"></label>
                <input asp-for="Blog.Date" class="form-control" readonly />
                <span asp-validation-for="Blog.Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Blog.UserId" class="form-control" readonly type="hidden" />
                <span asp-validation-for="Blog.UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Blog.Popularity" class="form-control" readonly type="hidden" />
                <span asp-validation-for="Blog.Popularity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Blog.SubcategoryId" class="form-control" readonly type="hidden" />
                <span asp-validation-for="Blog.SubcategoryId" class="text-danger"></span>
            </div>
        
            <div class="form-group">
                <input type="file" class="form-control" name="UploadedImage">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Pages/ViewForumPost.cshtml
@page
@model PublicProject.Pages.ViewForumPostModel
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    ViewData["Title"] = "Inlägg";
    var user = await UserManager.GetUserAsync(User);
}

    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Agency - Start Bootstrap Theme</title>
        <!-- Favicon-->
         <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
       <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
       <link href="css/black/styles.css" rel="stylesheet" />
    <link href="css/CommentStyle/Comment.css" rel="stylesheet" />
    </head>

<body>
<div class="blog-content">
    <div class="blog-pop">
        <div class="container">
            <strong><img class="test" width="30px" height="30px" src="~/img/viewcount.png" /> @Model.ScopedData.blog.Popularity</strong>
        </div>
    </div>
</div>
@*Om koden inte funkar här så ska koden från rad 37 till 39 ner till rad 58.*@
@{
    var skribent = Model.ScopedData.UserProfiles.FirstOrDefault(x => x.UserId == Model.ScopedData.blog.UserId);

    @*Koden under fixade så att man kunde titta på en blog post utan att vara inloggad*@
    @if (user != null)
    {
        var userProfile = Model.ScopedData.UserProfiles.FirstOrDefault(n => n.UserId == user.Id);
    }
}

@if (SignInManager.IsSignedIn(User))
{
    @if (Model.ScopedData.blog.UserId == user.Id)
    {
        <a asp-page="/EditBlog" asp-route-id="@Model.ScopedData.blog.Id">Redigera inlägg</a>
    }
}


<!-- Masthead-->
<header class="masthead">
    <div class="container">
        <div class="masthead-heading text-uppercase">@Model.ScopedData.blog.Title</div>
        <img class="img-fluid" src="~/img/@Model.ScopedData.blog.Image" />
        <div class="masthead-subheading"> @Model.ScopedData.blog.Text</div>
    </div>
</header>

<!-- About-->
<section class="page-section" id="about">
    <div class="container">
        <div class="text-center">
            @if(skribent != null)
            {
                <a asp-page="/SendmessageToUserView" asp-route-id="@skribent.UserId"><h3 class="section-heading text-uppercase">Skriven av @skribent.UserName </h3></a>
            }
            <h3 class="section-subheading text-muted">@Model.ScopedData.blog.Date</h3>
        </div>
    </div>
</section>
<!--Comment section-->
@{
    var comments = Model.ScopedData.Comments.Where(x => x.BlogId == Model.ScopedData.blog.Id);
}

@foreach(var sortedcomment in comments)
{
    <div class="comment">
        @{
            var image = Model.ScopedData.UserProfiles.FirstOrDefault(x => x.UserId == sortedcomment.UserId);
        }
        <div class="thumbnail">
            <img src="~/img/@image.Imglink" >
        </div>
            <h2 class="comment-content">@sortedcomment.Text</h2>
        <a class="comment" asp-page="/Sendmessagetouserview" asp-route-id="@sortedcomment.UserId">@sortedcomment.Author</a> | @sortedcomment.Date
        <div class="row">
                <div class="col-md-4">
                @if (SignInManager.IsSignedIn(User))
                {
                    var hasUsername = Model.ScopedData.UserProfiles.FirstOrDefault(n => n.UserId == user.Id);
                    if (hasUsername != null)
                    {
                        <form method="post" asp-page-handler="Report">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <input asp-for="Report.reporterId" value="@user.Id" readonly class="form-control" type="hidden" />
                            <span asp-validation-for="Report.reporterId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input asp-for="Report.reportedId" value="@sortedcomment.UserId" readonly class="form-control" type="hidden" />
                            <span asp-validation-for="Report.reportedId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    <label asp-for="Report.Text" class="control-label">Anledning</label>
                                    <input asp-for="Report.Text" class="form-control" />
                                    <span asp-validation-for="Report.Text" class="text-danger"></span>
                                </div>
                            <div class="form-group">
                                <input asp-for="Report.CommentId" value="@sortedcomment.Id" type="hidden" readonly class="form-control" />
                                <span asp-validation-for="Report.CommentId" class="text-danger"></span>
                            </div>
                                <div class="col-md-6">
                                    <label>&nbsp;</label>
                                    <input type="submit" value="Anmäl" class="btn btn-danger" />
                                </div>
                            </div>
                        </div>
                    </form>
                    }
                    else
                    {
                        <p style="color: red">Var vänlig och gå över till <a href="~/overview">UserProfile</a> för att registrera ett användarnamn för att få tillgång till alla funktioner!</p>
                    }
                }
                </div>
            </div>
        </div>
    }
@{
    int commentId = Model.ScopedData.Comments.Count() + 1;    
}

@if (SignInManager.IsSignedIn(User))
{
    var hasUsername = Model.ScopedData.UserProfiles.FirstOrDefault(n => n.UserId == user.Id);

    @*Finns ett bugg här, jag kan se kommentarfältet även fast mitt konto inte har ett användar namn*@
    if(hasUsername != null)
    {
        <div class="comment-form">
            <h2>Kommentera foruminlägg</h2>
            <form method="post" asp-page-handler="SendComment">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <input asp-for="Comment.Id" value="@commentId" class="form-control" readonly type="hidden" />
                    <span asp-validation-for="Comment.Id" class="text-danger"></span>
                </div>
                <div class="form-group">
                    @{
                        var commenter = Model.ScopedData.UserProfiles.FirstOrDefault(x => x.UserId == user.Id);
                        if (commenter?.UserName != null)
                        {
                            <input asp-for="Comment.Author" value="@commenter.UserName" class="form-control" readonly type="hidden" />
                            <span asp-validation-for="Comment.Author" class="text-danger"></span>
                        }
                    }
                </div>
                <div class="form-group">
                    <label asp-for="Comment.Text" class="control-label"></label>
                    <input asp-for="Comment.Text" class="form-control" />
                    <span asp-validation-for="Comment.Text" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="Comment.Date" value="@DateTime.Now" class="form-control" readonly type="hidden" />
                    <span asp-validation-for="Comment.Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="Comment.BlogId " value="@Model.ScopedData.blog.Id" class="form-control" readonly type="hidden" />
                    <span asp-validation-for="Comment.BlogId" class="text-danger"></span>
                    <div class="form-group">
                        <input asp-for="Comment.UserId" value=@user.Id readonly type="hidden" class="form-control" />
                        <span asp-validation-for="Comment.UserId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Skicka" class="btn btn-primary" />
                    </div>
            </form>
        </div>
    }
    else
    {
        <p style="color: red">Var vänlig och gå över till <a href="~/overview">UserProfile</a> för att registrera ett användarnamn för att kommentera bloggar!</p>
    }
}





<!-- Footer-->
<footer class="footer">
    <div class="footer-wrap">
        <div id="footer-text">
            &copy; 2023 - Snackis - <a asp-area="" asp-page="/Privacy">Integritet</a>
        </div>
        <a href="#top" id="btt">Top <i class="fa fa-chevron-up"></i></a>
    </div>
</footer>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
</body>